### ISSUE TITLE
Information: With XAMPP all is ok, online not, part II

### ISSUE THREAD

**Issue by jobrat** [sprain/php-swiss-qr-bill#207] opened 2022-11-06 10:18 UTC
First: thank you for this excellent library!

It is not an issue of swiss-qr-bill, perhaps someone has the same problem.

Local all was well, online i found finally this error: 'Index invalid or out of range'. I found the solution here: 

[https://github.com/Bacon/BaconQrCode/issues/92](url)

php ini:
opcache.jit_buffer_size=512M
opcache.jit=function

didn't work for me but with:
opcache.enable=OFF
on the folder where the swiss-qr-bill examples run it works.

My knowledge of opcache is to small to find the exact parameter.

**Comment by kohlerdominik** [comment] 2022-11-06 10:29
So it looks like this is a JIT issue. There are a couple of them [reportet](https://github.com/php/php-src/issues?q=is%3Aissue+is%3Aopen+JIT).

I personally wouldn't recommend to turn off opcache, if it's not absolutely necessary. Disabeling opcache might result in a major performance hit. can you try this directives:
```
opcache.enable=1
opcache.jit=off
```

**Comment by sprain** [comment] 2022-11-06 10:53
There is some qr code related discussion about this available here:
https://github.com/Bacon/BaconQrCode/issues/92

Conclusion is also that it's an issue with OpCache.

Closing this therefore, as based on current knowledge the issue is not related to this library.

**Closed by sprain** 2022-11-06 10:53 UTC
Labels: support

**Comment by jobrat** [comment] 2022-11-06 10:55
Thank you!
 

opcache.jit=off and opcache.jit=disable turn automatically back to opcache.jit=tracing. opcache.jit=function remains but the error: 'Index invalid or out of range' remains also.
Even if opcache.enable=0 opcache.jit=traing.
I will call hostpoint.ch on Monday.
