### ISSUE TITLE
Qr code sometimes not showing

### ISSUE THREAD

**Issue by Warwick5** [sprain/php-swiss-qr-bill#204] opened 2022-11-01 13:51 UTC
Hi
I'm the first time in here and hope to find someone who can explain how it all works.

I'm using the php-swiss-qr-bill library in two different applications in two different domains.

For some month now, it all works just fine. But now, as strange es it may sounds, sometimes the QR-code just does not appear in both applications. Without any error messages. And some hours or days later it works again, without any interaction.

When I started some month ago, I used the "composer require sprain/swiss-qr-bill" to setup the "vendor" directory. And for some reason it works just like that. 

I'm not sure now, if I have to do this "composer require sprain/swiss-qr-bill" for each of my two applications? Or can I just copy the "vendor" directory and the two composer.json and composer.lock to the second application?

I just don't know how it all works. If I download the package "php-swiss-qr-bill-master.zip" what is the proper procedure to start from scratch and create with the composer an new setup "vendor" directory. Are there any step by step guidelines?

I don't know where I have to put the downloaded php-swiss-qr-bill-master files and how the composer really works and finds the necessary files from the php-swiss-qr-bill-master. 

But the mail question is, can anyone tell me, why the QR-Codes work sometimes and not other times? 

Thank you ever so much for your help. To put it all mildly, I'm really frustrated that I don't understand the whole setup correctly.

**Comment by sprain** [comment] 2022-11-01 14:34
> I just don't know how it all works. If I download the package "php-swiss-qr-bill-master.zip" what is the proper procedure to start from scratch and create with the composer an new setup "vendor" directory. Are there any step by step guidelines?

With Composer, you do not need to download the package. The procedure is as follows:
1. Install Composer
2. Define and install the packages you need. There are two ways to do so:
  * Either define them in `composer.json` and run `composer install`
  * Or run `composer require sprain/swiss-qr-bill`
  
You can [find the documentation here](https://getcomposer.org/doc/01-basic-usage.md) (which in my opinion is a bit complicated and could be more beginner-friendly).

> But the mail question is, can anyone tell me, why the QR-Codes work sometimes and not other times?

This I really can't say based on the available information. Maybe we be able to help you debugging. As a start:
  * What `Output` of this library are you using?
  * Do you know whether your are creating the qr code in png format or in svg?
  * Can you reproduce the bevaviour? For example, does one specific invoice always have no qr code?

**Comment by Warwick5** [comment] 2022-11-01 15:01
Hi Manuel

 

Thanks a lot for your answer.

 

I have composer installed and run composer require sprain/swiss-qr-bill. And this created the directory “vendor” in the application. I just read in the documentation you sent me. It is now a bit more clear. 

 

So, I don’t have to download the package, composer does that for me.

 

*	I use the fpdf-example.php Output
*	I actually create both qr code in png and in svg format. I was not sure which one to choose. 
*	Yes, when the QR code is not displayed in the invoice, I can reproduce the behaviour many times. And as I mentioned. Sometimes it just works fine.

 

I really do appreciate your help.

 

 

 

Von: Manuel Reinhard ***@***.***> 
Gesendet: Dienstag, 1. November 2022 15:35
An: sprain/php-swiss-qr-bill ***@***.***>
Cc: Warwick5 ***@***.***>; Author ***@***.***>
Betreff: Re: [sprain/php-swiss-qr-bill] First steps with the php-swiss-qr-bill library (Issue #204)

 

I just don't know how it all works. If I download the package "php-swiss-qr-bill-master.zip" what is the proper procedure to start from scratch and create with the composer an new setup "vendor" directory. Are there any step by step guidelines?

With Composer, you do not need to download the package. The procedure is as follows:

1.	Install Composer
2.	Define and install the packages you need. There are two ways to do so:

*	Either define them in composer.json and run composer install
*	Or run composer require sprain/swiss-qr-bill

You can find the documentation here <https://getcomposer.org/doc/01-basic-usage.md>  (which in my opinion is a bit complicated and could be more beginner-friendly).

But the mail question is, can anyone tell me, why the QR-Codes work sometimes and not other times?

This I really can't say based on the available information. Maybe we be able to help you debugging. As a start:

*	What Output of this library are you using?
*	Do you know whether your are creating the qr code in png format or in svg?
*	Can you reproduce the bevaviour? For example, does one specific invoice always have no qr code?

**Comment by Warwick5** [comment] 2022-11-01 15:05
I forgot to mention, if there is no qr code, then it does not work on any invoice. So, it is not really invoice dependent. 

 

Von: Manuel Reinhard ***@***.***> 
Gesendet: Dienstag, 1. November 2022 15:35
An: sprain/php-swiss-qr-bill ***@***.***>
Cc: Warwick5 ***@***.***>; Author ***@***.***>
Betreff: Re: [sprain/php-swiss-qr-bill] First steps with the php-swiss-qr-bill library (Issue #204)

 

I just don't know how it all works. If I download the package "php-swiss-qr-bill-master.zip" what is the proper procedure to start from scratch and create with the composer an new setup "vendor" directory. Are there any step by step guidelines?

With Composer, you do not need to download the package. The procedure is as follows:

1.	Install Composer
2.	Define and install the packages you need. There are two ways to do so:

*	Either define them in composer.json and run composer install
*	Or run composer require sprain/swiss-qr-bill

You can find the documentation here <https://getcomposer.org/doc/01-basic-usage.md>  (which in my opinion is a bit complicated and could be more beginner-friendly).

But the mail question is, can anyone tell me, why the QR-Codes work sometimes and not other times?

This I really can't say based on the available information. Maybe we be able to help you debugging. As a start:

*	What Output of this library are you using?
*	Do you know whether your are creating the qr code in png format or in svg?
*	Can you reproduce the bevaviour? For example, does one specific invoice always have no qr code?

**Comment by Warwick5** [comment] 2022-11-01 16:11
*	I’m using Hostpoint.ch as the hosting provider
*	I’m running on PHP 8.1

 

It is rather strange. At the moment the codes are being displayed on both applications.

 

 

Von: Manuel Reinhard ***@***.***> 
Gesendet: Dienstag, 1. November 2022 17:07
An: sprain/php-swiss-qr-bill ***@***.***>
Cc: Warwick5 ***@***.***>; Author ***@***.***>
Betreff: Re: [sprain/php-swiss-qr-bill] First steps with the php-swiss-qr-bill library (Issue #204)

 

Yes, when the QR code is not displayed in the invoice, I can reproduce the behaviour many times.
I forgot to mention, if there is no qr code, then it does not work on any invoice. So, it is not really invoice dependent.

So it depends on … time? This would be very strange.

*	What hosting provider are you using?
*	What php version are you running there?

**Comment by Warwick5** [comment] 2022-11-02 07:07
Good morning. A short update to the case. Last night all the qr codes where shown in both the applications. Not so this morning. One app works fine that other does't show any qr codes in the invoice.

Could it be on my way of coding? I have to tel you that I'm not an advanced php programmer.

the calling script looks like this:
echo "<iframe src='https://www.app.physio-und-sport.ch/maint_abo_qr_rechnung_check_2.php?name=$name&strasse=$kunde_strasse&ort=$ort&plz=$plz&abo=$kunde_abo&abo_preis=$abo_preis' width='700' height='500' frameborder='0'></iframe>";

and the receiving code where the qr is displayes I will attach.

[maint_abo_qr_rechnung_check_2.txt](https://github.com/sprain/php-swiss-qr-bill/files/9917417/maint_abo_qr_rechnung_check_2.txt)

I hope it makes sence to you.

I really do appreciate your help.

**Comment by sprain** [comment] 2022-11-02 08:22
Small note: In your code you are defining an `FpdfOutput`, but a few lines later your are overwriting it with a `HtmlOutput`.

But … this has nothing to do with the problem you are experiencing. If the exact same invoice data once works and once does not, then your code is not the problem.

It could be something on the server. Since you are actually outputing a HtmlOutput, it could also be something in your browser.

* When the problem occurs, have you tried different browsers? Do they behave the same?

The next time you see an invoice without a qr code …
* make a screenshot
* copy the exact url from your iframe
* again take the code that you used to generate this invoice

… and post it all here again. Maybe we can help.
Of course, considering any privacy issues. Please do not post data of actual customers of yours here.

**Comment by Warwick5** [comment] 2022-11-02 09:08
Yes, I used different browsers with the same result.

Thanks for pounting this out that in my code I overwrite FpdfOutput with HtmlOutput. I don't know the exact diffent of the two and as the HtmlOutput worked, I used it. Would it be better to change to FpdfOutput?

Attached a screenshot of the other application where the qr code is not shown. The code is the ecact same just in an other application.

echo "<iframe src='https://www.wochenbett-baden.ch/qr_rechnung_anzeigen.php?
                                    user_vorname=$user_vorname&user_name=$user_name&user_strasse=$user_strasse&user_plz=$user_plz&user_ort=$user_ort&user_iban=$user_iban
                                    &name=$name&strasse=$strasse&ort=$ort&plz=$plz&type=$type&preis=$preis'  width='650' height='500' frameborder='0'></iframe>";


![Screenshot 2022-11-02 095801](https://user-images.githubusercontent.com/93274012/199449002-dabc2ba8-0046-4894-b5ef-0bd5ec0c5a63.jpg)

As I mentioned before, today the qr code is shown in the other application.

**Comment by sprain** [comment] 2022-11-02 09:36
> Thanks for pounting this out that in my code I overwrite FpdfOutput with HtmlOutput. I don't know the exact diffent of the two and as the HtmlOutput worked, I used it. Would it be better to change to FpdfOutput?

It depends whether you want to generate the invoice as a PDF or in HTML :) Likely you will want a PDF.

> Attached a screenshot of the other application where the qr code is not shown. The code is the ecact same just in an other application.

So, the _whole payment part_ is not showing, not just the qr code on the invoice?
This probably means there is some invalid data then.

If possible, provide an url with actual values that causes the errors, not just containing your variables. You might be able to find this url by right-clicking in the iFrame and opening it in a new window.

**Comment by Warwick5** [comment] 2022-11-02 10:06
Yes, the whole payment part is not showing.

But why is it showing the data correct one time and not the other time? 

Here the iFrame right-click data. I hope that is what you requested.

view-source:https://www.wochenbett-baden.ch/qr_rechnung_anzeigen.php?%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20user_vorname=Deborah&user_name=Silva%20dos%20Santos&user_strasse=R%C3%B6merstrasse%2022&user_plz=5400&user_ort=Baden&user_iban=CH76%200900%200000%204076%207959%203%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20&name=Bernadette%20Recher&strasse=Tiefenmattstrasse%2045&ort=H%C3%B6lstein&plz=4434&type=Rechnung%20314&preis=77.45

**Comment by Warwick5** [comment] 2022-11-02 12:43
Let me tell you what I have done today, always with the same code:

1) I run "composer require sprain/swiss-qr-bill" in the root directory of the application "A" and copied the created "vendor" directory and the two files "composer.json" and "composer.lock" to the server. The payments with the qr code did not show.

2) I copied the "vendor" directory and the two files "composer.json" and "composer.lock" from the application "B" that works today, into the app "A". Same sesult.

3) I copied from an old backup the "vendor" directory and the two files "composer.json" and "composer.lock" to App "A" and it works now for all payments.

Even thou, I have done option 3) yesterday and it didn't work.

For my understanding:
1) Can I copy the "vendor" directory from the application "B" that works just now, to the other app "B"?

2) Would it be best to use "composer require sprain/swiss-qr-bill" to generate the "vendor" directory in both applications?

3) When I want to have the whole payment including the qr code on the screen, is it best to use the HtmlOutput?

**Comment by sprain** [comment] 2022-11-02 15:10
> Here the iFrame right-click data. I hope that is what you requested.

Your url results in an empty page. This could be because of the error we are looking for. Do you maybe have any information in the log files of the server.

> Can I copy the "vendor" directory from the application "B" that works just now, to the other app "B"?
> Would it be best to use "composer require sprain/swiss-qr-bill" to generate the "vendor" directory in both applications?

With Composer, it's always recommended to install packages with composer and not do any copying of files. Composer does more than download files. It also creates your autoload file based on your project.

> When I want to have the whole payment including the qr code on the screen, is it best to use the HtmlOutput?

It really depends on your use case and what people should do with the invoice. There is no right or wrong. You choose the output that works best for your project. I recommend you dig in some more into composer documentation and learn some more about this great tool.

I think we have reached the end of what we can do here with the available information. I will close this issue now. Feel free to re-open if you can provide any new relevant information, like an actual error message for example.

**Closed by sprain** 2022-11-02 15:10 UTC
Labels: support

**Comment by Warwick5** [comment] 2022-11-03 11:46
I'm terribly sory to bother you again. I must get this going and it just doesn't work.

1) I scratched the vendor directory

2) In composer composer require sprain/swiss-qr-bill
 
3) Installed the "example.php" and added the "html-example.php" and it worked fine

4) Then I added the data to the example.php and put this into the production application. It also worked fine. The people did print many payments.

5) About 2 hours later, it did not work again. The whole payment ist not showing and I don't get any error messages.

6) I installed the "example.php" with the "html-example.php" again and it does not work, with the same result. So it can't be my data.

I noticed, that the two files are not being saved.
    $qrBill->getQrCode()->writeFile(__DIR__ . '/qr.png');
    $qrBill->getQrCode()->writeFile(__DIR__ . '/qr.svg');

[example.txt](https://github.com/sprain/php-swiss-qr-bill/files/9927947/example.txt)

I don't know how to produce an error message. I'm just stuck.

**Comment by sprain** [comment] 2022-11-03 15:48
> I noticed, that the two files are not being saved.

You could check whether the directory where you want to save the qr code is writable. If you use the example code, this would be the same directory where `html-example.php` is stored.

> I must get this going and it just doesn't work.

I understand your pain. Unfortunately, the possibilties to debug your specific setup are limited, as the cause must be outside of this library. Maybe eventually you will need to get some professional help from a local web agency. I am sure there are many around where you live.
